# Generated by Django 4.2.17 on 2025-01-09 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_type', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], max_length=10)),
                ('abnormal_subtype', models.CharField(blank=True, choices=[('Super voider', 'Super voider'), ('Compressive', 'Compressive'), ('Constricture', 'Constricture'), ('Interrupted', 'Interrupted'), ('Staccato', 'Staccato')], max_length=20, null=True)),
                ('label_time', models.DateTimeField(auto_now_add=True)),
                ('csv_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='homepage.csvdata')),
                ('labeled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labeled_entries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('csv_data', 'user')},
            },
        ),
    ]
