# Generated by Django 4.2.17 on 2025-01-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labelpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set(),
        ),
    ]
