# Generated by Django 4.2.17 on 2025-01-10 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labelpage', '0003_alter_label_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set(),
        ),
    ]
