# Generated by Django 4.2.17 on 2025-01-11 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labelpage', '0005_alter_label_unique_together_label_unique_csv_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
