# Generated by Django 4.2.17 on 2025-01-12 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0003_remove_csvdata_unique_image_user_and_more'),
        ('labelpage', '0006_alter_label_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='label',
            name='unique_csv_user',
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('csv_data', 'labeled_by')},
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('csv_data', 'labeled_by'), name='unique_csv_labeled_by'),
        ),
        migrations.RemoveField(
            model_name='label',
            name='user',
        ),
    ]
