# Generated by Django 4.2.17 on 2025-01-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelpage', '0007_remove_label_unique_csv_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='abnormal_subtype',
            field=models.CharField(blank=True, choices=[('Super voider', 'Super voider'), ('Compressive', 'Compressive'), ('Constrictive', 'Constrictive'), ('Interrupted', 'Interrupted'), ('Staccato', 'Staccato')], max_length=20, null=True),
        ),
    ]
