# Generated by Django 4.2.17 on 2025-01-09 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_number', models.IntegerField(unique=True)),
                ('max_flow_rate', models.FloatField()),
                ('max_flow_rate_unit', models.CharField(default='ml/s', max_length=20)),
                ('average_flow_rate', models.FloatField()),
                ('average_flow_rate_unit', models.CharField(default='ml/s', max_length=20)),
                ('increase_time', models.FloatField()),
                ('increase_time_unit', models.CharField(default='s', max_length=20)),
                ('total_volume_voided', models.FloatField()),
                ('total_volume_voided_unit', models.CharField(default='ml', max_length=20)),
                ('total_voiding_time', models.FloatField()),
                ('total_voiding_time_unit', models.CharField(default='s', max_length=20)),
                ('total_flow_time', models.FloatField()),
                ('total_flow_time_unit', models.CharField(default='s', max_length=20)),
                ('time_samples', models.TextField()),
                ('flowrate_samples', models.TextField()),
                ('image_filename', models.CharField(max_length=255, unique=True)),
                ('csv_file', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_resource', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csv_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
