# Generated by Django 4.2.17 on 2025-01-10 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='csv_file',
            field=models.CharField(default='flowrate_parameters.csv', max_length=255),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='image_filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='image_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csv_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='csvdata',
            unique_together={('image_filename', 'user')},
        ),
        migrations.AddConstraint(
            model_name='csvdata',
            constraint=models.UniqueConstraint(fields=('image_filename', 'user'), name='unique_image_user'),
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='is_resource',
        ),
    ]
