# Generated by Django 4.2.17 on 2025-01-12 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0002_alter_csvdata_csv_file_alter_csvdata_image_filename_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='csvdata',
            name='unique_image_user',
        ),
        migrations.AlterUniqueTogether(
            name='csvdata',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to=homepage.models.user_csv_file_path),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='csv_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='csvdata',
            constraint=models.UniqueConstraint(fields=('user', 'image_filename'), name='unique_user_csv'),
        ),
    ]
