# Generated by Django 4.2.17 on 2025-01-12 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0003_remove_csvdata_unique_image_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csv_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
