# Generated by Django 4.2.17 on 2025-01-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_csvdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csvdata',
            name='sex',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
